### PR TITLE
Create prebuilt binaries using `prebuild`

### LINKED ISSUE #40: Distribute pre-built binaries
Hello! :wave:

I'm the co-author of an npm module called [`elgato-stream-deck`](https://github.com/Lange/node-elgato-stream-deck) which provides an API for a specific hardware device. We're working on a [pull request](https://github.com/Lange/node-elgato-stream-deck/pull/27#discussion_r117613900) to add support for detecting when Stream Deck devices are plugged or unplugged, and `node-usb-detection` is a perfect fit for what we're trying to do.

However, compiling `node-usb-detection` requires a **lot** of dependencies on Windows, which means that installing `elgato-stream-deck` is difficult for users. Is there any possibility that we could assist in getting pre-built binaries set up for this module, to avoid end users needing to install a full compiler toolchain?

Thanks for this module! 👍

### PR DESCRIPTION
**Pull request by Lange**
Closes #40.

This PR should provide almost everything needed to immediately start getting pre-built binaries automatically created and uploaded to GitHub for the following platforms:

- [x] Windows x86
- [x] Windows x64
- [x] Linux x86
- [x] Linux x64
- [x] macOS x64

Before merging, you'll want to set up this project on both AppVeyor and TravisCI. This should be just a few mouse clicks, all you're doing is telling these services that yes, you would like to build this project. You don't need to do any configuration at this time.

Once that's done, you'll need to replace my encrypted GitHub token (the `prebuild_upload` environment variable) with your own:

1. Follow the steps outlined in the [prebuild docs](https://github.com/prebuild/prebuild#create-github-token) for creating a GitHub token with the appropriate scope permissions.
2. Use the [AppVeyor "Encrypt Data" page](https://ci.appveyor.com/tools/encrypt) to encrypt your token. Then, paste it over my encrypted token in line 4 of `appveyor.yml`.
3. [Install the TravisCI CLI.](https://github.com/travis-ci/travis.rb#installation)
4. From your local `node-usb-detection` directory, run the following command to get your encrypted `prebuild_upload` env var with your token:

    ```bash
    travis encrypt prebuild_upload=YOUR_GITHUB_TOKEN_HERE
    ```
5. Copy the resulting output and paste it over mine in line 22 of `.travis.yml`.
6. Commit/push your changes, then merge this PR! :tada: If I've done everything right, tagged commits will trigger a build, and automatically publish their artifacts to the GitHub release. The release will also be created if it does not already exist.

Caveats:
- Travis' OSX build infrastructure is pretty overwhelmed at this point. On bad days it can take upwards of 5 hours for an OSX build to start. At night it settles down and you can usually get your build started immediately. You can look at the graphs on https://www.traviscistatus.com/ to get a feel for the patterns of when their infrastructure is completely slammed.

Credits:
- I used pretty much all of the CI configs from [`node-serialport`](https://github.com/node-serialport/node-serialport) as a base. I made very few modifications to them.

### CODE REVIEW

**Comment by Lange** [comment]
Oh, this also includes a pretty comprehensive testing matrix for once we actually have tests that are okay for CI. In the meantime, this matrix just ensures that everything at least compiles.

**Comment by lovell** [comment]
@Lange You should be able to simplify the Travis CI config by by switching to an Ubuntu 14.04 image and removing the manual `g++-4.8` boilerplate - see https://docs.travis-ci.com/user/reference/trusty/

**Comment by Lange** [comment]
@lovell Good call! I've gone ahead and made that simplification. I'm not very knowledgable on C/C++ in general, but I _think_ I did the correct thing by leaving the `g++-4.8-multilib` and `gcc-multilib` packages in the apt config?

**Comment by Lange** [comment]
I was able to further simplify the build config and get away with installing fewer apt packages. The build times are now wicked fast on Linux:

image

**Comment by MadLittleMods** [comment]
Thanks for the contribution @Lange ❤️ 

Merged via https://github.com/MadLittleMods/node-usb-detection/commit/b49c568fa3e60a9098717319ac6375a874951985 🚀 

First set of builds on a tagged release here, https://github.com/MadLittleMods/node-usb-detection/releases/tag/v1.4.1 😎 

---

We should add some documentation to the README around our new binary builds and how to use them. I understand you can `require('detection.node')` directly. Is there a popular pattern for downloading and requiring prebuilt binaries?

I noticed the binaries don't seem to be fully-functional with the `eventemitter2` properties missing 😕.

```js
var usbDetect = require('./detection.node');

// Results in `TypeError: usbDetect.on is not a function`
usbDetect.on('add', function(device) { console.log('add', device); });
```

**Comment by Lange** [comment]
@MadLittleMods All the installation is handled automatically by `prebuild-install`, which is already set up in the npm scripts. No further user action should be necessary if I've set everything up correctly.

**Comment by MadLittleMods** [comment]
@Lange 😮 Fancy! 

I'm noticing that the install just hangs after it prints the `Successfully installed prebuilt binary!` message. Are things installing correctly for you?

```
$ npm install usb-detection --save

> usb-detection@1.4.1 install C:\Users\MLM\Downloads\usb-detection-install-test3\node_modules\usb-detection
> prebuild-install || node-gyp rebuild

prebuild-install info begin Prebuild-install version 2.3.0
prebuild-install info looking for local prebuild @ prebuilds\usb-detection-v1.4.1-node-v48-win32-x64.tar.gz
prebuild-install info looking for cached prebuild @ C:\Users\MLM\AppData\Roaming\npm-cache\_prebuilds\https-github.com-MadLittleMods-node-usb-detection-releases-download-v1.4.1-usb-detection-v1.4.1-node-v48-win32-x64.tar.gz
prebuild-install http request GET https://github.com/MadLittleMods/node-usb-detection/releases/download/v1.4.1/usb-detection-v1.4.1-node-v48-win32-x64.tar.gz
prebuild-install http 200 https://github.com/MadLittleMods/node-usb-detection/releases/download/v1.4.1/usb-detection-v1.4.1-node-v48-win32-x64.tar.gz
prebuild-install info downloading to @ C:\Users\MLM\AppData\Roaming\npm-cache\_prebuilds\https-github.com-MadLittleMods-node-usb-detection-releases-download-v1.4.1-usb-detection-v1.4.1-node-v48-win32-x64.tar.gz.20984-0d339e9b36bc3.tmp
prebuild-install info renaming to @ C:\Users\MLM\AppData\Roaming\npm-cache\_prebuilds\https-github.com-MadLittleMods-node-usb-detection-releases-download-v1.4.1-usb-detection-v1.4.1-node-v48-win32-x64.tar.gz
prebuild-install info unpacking @ C:\Users\MLM\AppData\Roaming\npm-cache\_prebuilds\https-github.com-MadLittleMods-node-usb-detection-releases-download-v1.4.1-usb-detection-v1.4.1-node-v48-win32-x64.tar.gz
prebuild-install info unpack resolved to C:\Users\MLM\Downloads\usb-detection-install-test3\node_modules\usb-detection\build\Release\detection.node
prebuild-install info unpack required C:\Users\MLM\Downloads\usb-detection-install-test3\node_modules\usb-detection\build\Release\detection.node successfully
prebuild-install info install Successfully installed prebuilt binary!
```

**Comment by Lange** [comment]
@MadLittleMods Oh, you're right. That can't be good. At this time I'm unsure what the cause of this could be

**Comment by Lange** [comment]
Got it, the problem is that this module doesn't let the node process exit by default, and prebuild does a test `require` of it to verify that it loads: https://github.com/prebuild/prebuild-install/pull/45#issuecomment-338723435

**Comment by MadLittleMods** [comment]
@Lange Ahh, nice catch! We would need to shove a `usbDetect.stopMonitoring();` in there somehow.

Because of the side-effects of the module currently when required, I think we should perhaps make a v2 with `usbDetect.startMonitoring()`. And make a new `usb-detect@1.4.2` release without the `prebuild-install`. wdyt?

**Comment by Lange** [comment]
@MadLittleMods I agree, that seems like the fastest way forward and a reasonable approach.

**Comment by Lange** [comment]
Though actually we don't need to make a new `1.4.2`, just delete the pre-build binaries from the github release and the existing `1.4.2` release will automatically fallback to building from source, same as usual.

**Comment by MadLittleMods** [comment]
@Lange and I chatted a bit more here, :point_up: [November 11, 2017 11:25 PM](https://gitter.im/MadLittleMods/node-usb-detection?at=5a07db46df09362e67f9eeef)

 - `1.4.2` released without `install` hook 🚀 https://github.com/MadLittleMods/node-usb-detection/pull/48
 - `2.x` with `startMonitoring` (PR incoming)
    - It looks like `startMonitoring` is already an available function but we also start things in `InitDetection` which gets called in the constructor `init` sorta thing which is causing the side-effects.
    - I would also like to get https://github.com/MadLittleMods/node-usb-detection/pull/46 wrapped up and shipped but that requires a bit more digging (help wanted)

**Pull request closed without merging**
