### PR TITLE
Use native Promises

### PR DESCRIPTION
**Pull request by timfish**
Node has had native promises since v4 so I don't think bluebird is required.

### CODE REVIEW

**Comment by MadLittleMods** [comment]
@timfish Seems fine. We should update the `engines` field in `package.json`, https://docs.npmjs.com/files/package.json#engines

**Comment by timfish** [comment]
Updated engines to >=4

**Comment by MadLittleMods** [comment]
Thanks @timfish ❤️ 

I looked through the code to make sure we weren't using any specific bluebird methods and ran the test suite ✔️

**Comment by MadLittleMods** [comment]
This is now part of v4.0.0 🚀 , https://github.com/MadLittleMods/node-usb-detection/blob/master/CHANGELOG.md#v400---2018-9-27

Waiting on the `prebuild` builds for the tag before pushing to npm, https://github.com/MadLittleMods/node-usb-detection/releases/tag/v4.0.0

**Pull request merged**
