### PR TITLE
fixed issue with node 0.10.x

### PR DESCRIPTION
**Pull request by apla**

### CODE REVIEW

**Comment by MadLittleMods** [comment]
@apla Do the tests pass? Can you outline what versions of node and what OS versions you tested this on?

**Comment by apla** [comment]
Mac OS X 10.11, node 0.10.x — pass,
Windows 10, node 0.12.x — pass,
Windows 8.1, node 5.5.x — pass

Actually I've not changed anything platform specific, only common code. I will test it on linux and Mac OS X with node 4.2.1 tomorrow

**Comment by apla** [comment]
Mac OS X 10.11, node 5.0.0 — pass,
Mac OS X 10.11, node 4.2.1 — pass,
Ubuntu Linux 15.10, node 4.3.1 — pass,
Ubuntu Linux 15.10, node 0.10.25 — pass

**Comment by apla** [comment]
I've tested multiple devices, USB com port adapter (cp2102), Mass Storage device (USB flash drive), everything is fine

**Comment by MadLittleMods** [comment]
Tests Passing on:

 - Windows 10, `node@5.5.0`
 - OSX 10.11.2, `node@4.2.3`
 - OSX 10.11.2, `node@0.10.43`
 - Ubuntu 14.04.03, `node@4.4.0` via VM
 - Ubuntu 14.04.03, `node@0.10.43` via VM

**Comment by MadLittleMods** [comment]
Merged:

 - https://github.com/MadLittleMods/node-usb-detection/commit/8d8300e3ef46d9269988b84ee9ee168bcacc14f9
 - https://github.com/MadLittleMods/node-usb-detection/commit/5ceb1cedb6a92775b18d4c2c4b3618f3d251da0d

**Comment by MadLittleMods** [comment]
Thank you for the contribution and testing @apla :grinning: 

I just made a release `v1.4.0` with these changes!

**Pull request closed without merging**
