### PR TITLE
Add support for Node 13

### PR DESCRIPTION
**Pull request by kryops**
Fixes https://github.com/MadLittleMods/node-usb-detection/issues/91

~~Note: Appveyor does support Node 12 now, but not yet Node 13: https://github.com/appveyor/ci/issues/3157~~

The tests are still flaky on my machine, so it would be good if someone could verify it on theirs :wink:

### CODE REVIEW

**Comment by orangeChu** [comment]
It seems that electron7 will have the same problem. Thank you for submitting it. :)

**Comment by andsmedeiros** [comment]
Any chances this is getting merged soon?

**Comment by yanfali** [comment]
I'm testing it now on Electron 7.1 and Node 12, compiles the node module now.

**Comment by kryops** [comment]
AppVeyor seems to support Node 13 now, I added it to the PR.

Until this is merged, you can point the dependency to the master branch of my fork to get Node 13 support (which will build it locally):

```
"usb-detection": "https://github.com/kryops/node-usb-detection.git"
```

**Comment by MadLittleMods** [comment]
Tested on Windows 10 with Node.js v13.2.0 ✔️ 

Thanks for the updates @kryops ❤️

**Comment by MadLittleMods** [comment]
[`usb-detection@4.6.0`](https://github.com/MadLittleMods/node-usb-detection/blob/master/CHANGELOG.md#460---2019-11-24) published to npm, https://www.npmjs.com/package/usb-detection

prebuilds:

 - https://travis-ci.org/MadLittleMods/node-usb-detection/builds/616424253
 - https://ci.appveyor.com/project/MadLittleMods/node-usb-detection/builds/29088116

**Pull request merged**
