### PR TITLE
usb device path

### PR DESCRIPTION
**Pull request by angelmic**
Hi, 

I added an attribute to solve #10 

I finished the code for Linux and Mac but could someone please implement it on Windows.

### CODE REVIEW

**Comment by MadLittleMods** [comment]
I think this should be its own library/package: Getting the device path.

On Windows, I believe there is no device path. In device manager, you can view "Devices by connection" which gives a tree like view but you can't access it with this information. For example on windows, to access a serial port it would be `COM3` (`/dev/ttyS2` on linux).

Once it is a separate package, we can discuss whether `usb-detection` should add the information to the device object.

**Comment by adrai** [comment]
+1 separate package + possible usage in here

**Comment by mgcrea** [comment]
Any updates on this? I'm really looking forward to have a cross-platform solution to detect and use mounted usb devices.

**Comment by MadLittleMods** [comment]
@mgcrea This feature will most likely end up in a separate package before we consider to bring it in. Feel free to post any package suggestions if you come across something.

**Comment by mbrammer** [comment]
Did anyone create a new package for this yet?
Couldn't find any way to get the path of a connected device.

**Comment by mikart143** [comment]
bump, I waiting for it to

**Pull request closed without merging**
